### tools
GET http://localhost:8080/observability/tools

### chat
GET http://localhost:8080/observability/chat

### embedding
GET http://localhost:8080/observability/embedding

### embedding generic
GET http://localhost:8080/observability/embedding/generic
