# Vidio API

### 文生视频

GET http://127.0.0.1:10081/ai/video/text

### 使用视频模板
GET http://127.0.0.1:10081/ai/video/tmpl

### 首帧生成
GET http://127.0.0.1:10081/ai/video/first

### 首尾帧生成
GET http://127.0.0.1:10081/ai/video/fl
