### Java Bean
GET http://localhost:10007/bean/chat

###
GET http://localhost:10007/bean/chat-format

###
GET http://localhost:10007/bean/chat-model-format

###
GET http://localhost:10007/bean/play

### JSON
GET http://localhost:10007/json/chat

###
GET http://localhost:10007/json/chat-format

### Mcp
GET http://localhost:10007/map-list/chatMap

###
GET http://localhost:10007/map-list/chatList
