###
GET http://localhost:10013/dashscope/multi/video

###
GET http://localhost:10013/dashscope/multi/image

###
GET http://localhost:10013/dashscope/multi/image/bin

###
GET http://localhost:10013/dashscope/multi//stream/image
