# Openai Chat API

### Chat Client Simple Chat
GET http://127.0.0.1:10003/openai/chat-client/simple/chat

### Chat Client Stream Chat
GET http://127.0.0.1:10003/openai/chat-client/stream/chat

### Chat Client Stream Chat Response
GET http://127.0.0.1:10003/openai/chat-client/stream/response

### Chat Model Simple Chat
GET http://127.0.0.1:10003/openai/chat-model/simple/chat

### Chat Model Stream Chat
GET http://127.0.0.1:10003/openai/chat-model/stream/chat

### Chat Model Custom Options Chat
GET http://127.0.0.1:10003/openai/chat-model/custom/chat

### Chat Model Standard JSON Mode Chat
GET http://127.0.0.1:10003/openai/chat-model/custom/chat/json-mode
