# STT(speech to text) API

### STT(speech to text) API
GET http://127.0.0.1:10009/ai/stt

### STT(speech to text) stream API
GET http://127.0.0.1:10009/ai/stt/stream

### STT(speech to text) async API
GET http://127.0.0.1:10009/ai/stt/async

# TTS(text to speech) API

### TTS(text to speech) API
GET http://127.0.0.1:10009/ai/tts

### TTS(text to speech) stream API
GET http://127.0.0.1:10009/ai/tts/stream
